#
# About: Default image for development, tests and basic examples
#

# Docker official image with docker-in-docker (dind)
FROM docker:stable-dind

RUN apk update && apk upgrade
# For an interactive shell

# Installed packages:
# - bash: Used by startShell method in DockerHost, used as the default interactive shell
# - iproute2: IP utilities to manage interfaces.
# - busybox-extras: Includes telnet, used by running iperf with Mininet's CLI
# - stress-ng: Updated version of stress (ref: https://www.cyberciti.biz/faq/stress-test-linux-unix-server-with-stress-ng/)
RUN apk add bash bash-completion
RUN apk add iproute2 busybox-extras iperf
RUN apk add stress-ng

ENV HOME /root
WORKDIR /root

# Define default command.
CMD ["bash"]
