#
# About: Test image for development
#

FROM ubuntu:18.04

RUN \
        apt-get update && \
        apt-get -y upgrade && \
        apt-get install -y build-essential && \
        apt-get install -y net-tools iproute2 iputils-ping \
        apt-transport-https ca-certificates curl stress iperf iperf3

# Install Docker from Docker Inc. repositories.
RUN curl -sSL https://get.docker.com/ | sh

# Install Python
RUN apt-get -y install python-pip python3.6

# Install Nano as Editor
RUN apt-get -y install nano

# Install numpy with pip3
RUN pip install numpy

ENV HOME /root
WORKDIR /root

# Define default command.
CMD ["bash"]

# Add Directories
ADD client.py /tmp/
ADD probe_agent.py /tmp/
ADD server.py /tmp/
ADD probe_server.py /tmp/
